services:
  h5web:
    build:
      context: ./h5web_app
      args:
        - H5GROVE_APP_PORT=${H5GROVE_APP_PORT}
        - H5WEB_APP_PORT=${H5WEB_APP_PORT}
    ports:
      - '${H5WEB_APP_PORT}:${H5WEB_APP_PORT}'
  h5grove:
    build:
      context: ./h5grove_app
      args:
        - H5GROVE_APP_PORT=${H5GROVE_APP_PORT}
    ports:
      - '${H5GROVE_APP_PORT}:${H5GROVE_APP_PORT}'
    volumes:
      - type: bind
        source: ./data
        target: /data
